extract install_dir to variable

diff --git a/docs/bootstrap b/docs/bootstrap
--- a/docs/bootstrap
+++ b/docs/bootstrap
@@ -5,6 +5,8 @@ set -uo pipefail
 umask 077
 TTY="/dev/$(ps -p $$ -o tty=)"
 
+install_dir="/var/lib/minecraft"
+
 ################################################################
 # Helper functions
 
@@ -111,28 +113,28 @@ ask "Do you agree to the EULA?" \
 
 if ! getent passwd minecraft &>/dev/null; then
 	status "Creating minecraft user"
-	useradd --system --home-dir /var/lib/minecraft --no-create-home minecraft \
+	useradd --system --home-dir $install_dir --no-create-home minecraft \
 		|| die "Could not create user 'minecraft'"
 fi
 
-mkdir -p /var/lib/minecraft
-chmod 700 /var/lib/minecraft
-chown minecraft: /var/lib/minecraft
+mkdir -p $install_dir
+chmod 700 $install_dir
+chown minecraft: $install_dir
 
 
 ################################################################
 # Setup repository
 
-if [[ -e /var/lib/minecraft/deploy ]]; then
-	echo "[33mThe deploy directory /var/lib/minecraft/deploy already exists."
+if [[ -e $install_dir"/deploy" ]]; then
+	echo "[33mThe deploy directory $install_dir/deploy already exists."
 	echo "You can still run the installer again, but it may overwrite some"
 	echo "configuration files if you edited them in the meantime.[m"
 	ask "Are you sure you want to continue?" \
 		|| die "Installation aborted."
 fi
 
-cd /var/lib/minecraft \
-	|| die "Could not change into /var/lib/minecraft"
+cd $install_dir \
+	|| die "Could not change into $install_dir"
 
 if [[ -e deploy ]]; then
 	status "Updating deploy repository"
@@ -243,7 +245,7 @@ fi
 
 if ask "Download all initial server files through update.sh?"; then
 	runuser -u minecraft -- ./update.sh < "$TTY" \
-		|| echo "Could not update server files, continuing later"
+		|| echo "Could not update server files, you need to manually do that later"
 fi
 
 
