make alt install dirs actually work

diff --git a/docs/bootstrap b/docs/bootstrap
--- a/docs/bootstrap
+++ b/docs/bootstrap
@@ -5,7 +5,7 @@ set -uo pipefail
 umask 077
 TTY="/dev/$(ps -p $$ -o tty=)"
 
-install_dir="/var/lib/minecraft"
+INSTALL_DIR="/var/lib/minecraft"
 declare -i server_port_range_offset=25500
 
 ################################################################
@@ -114,28 +114,28 @@ ask "Do you agree to the EULA?" \
 
 if ! getent passwd minecraft &>/dev/null; then
 	status "Creating minecraft user"
-	useradd --system --home-dir $install_dir --no-create-home minecraft \
+	useradd --system --home-dir $INSTALL_DIR --no-create-home minecraft \
 		|| die "Could not create user 'minecraft'"
 fi
 
-mkdir -p $install_dir
-chmod 700 $install_dir
-chown minecraft: $install_dir
+mkdir -p $INSTALL_DIR
+chmod 700 $INSTALL_DIR
+chown minecraft: $INSTALL_DIR
 
 
 ################################################################
 # Setup repository
 
-if [[ -e $install_dir"/deploy" ]]; then
-	echo "[33mThe deploy directory $install_dir/deploy already exists."
+if [[ -e $INSTALL_DIR"/deploy" ]]; then
+	echo "[33mThe deploy directory $INSTALL_DIR/deploy already exists."
 	echo "You can still run the installer again, but it may overwrite some"
 	echo "configuration files if you edited them in the meantime.[m"
 	ask "Are you sure you want to continue?" \
 		|| die "Installation aborted."
 fi
 
-cd $install_dir \
-	|| die "Could not change into $install_dir"
+cd $INSTALL_DIR \
+	|| die "Could not change into $INSTALL_DIR"
 
 if [[ -e deploy ]]; then
 	status "Updating deploy repository"
@@ -267,7 +267,7 @@ fi
 # Install systemd services
 
 status "Installing service files"
-./contrib/install.sh < "$TTY" \
+./contrib/install.sh "$INSTALL_DIR/deploy" < "$TTY" \
 	|| die "Error while installing service files"
 
 
